CAT_FEATURES = ['CCHV_1', 'CCHV_2', 'CCHV_3', 'CCHV_4', 'CCHV_5', 'CCHV_6', 'pass_avsc']

ANOTHER_COLS = ['dtb_mean', 'dtb_std', 'dtb_diff','drl_mean', 'drl_std', 'sotchk_mean']

NUM_FEATURES_OG =[
    'HK1_drl',
    'HK2_drl',
    'HK3_drl',
    'HK4_drl',
    'HK5_drl',
    'HK6_drl',
    'HK7_drl',
    'HK8_drl',
    'HK9_drl',
    'HK10_drl',
    'HK11_drl',
    'HK12_drl',
    'HK1_dtbhk',
    'HK2_dtbhk',
    'HK3_dtbhk',
    'HK4_dtbhk',
    'HK5_dtbhk',
    'HK6_dtbhk',
    'HK7_dtbhk',
    'HK8_dtbhk',
    'HK9_dtbhk',
    'HK10_dtbhk',
    'HK11_dtbhk',
    'HK12_dtbhk',
    'HK1_sotchk',
    'HK2_sotchk',
    'HK3_sotchk',
    'HK4_sotchk',
    'HK5_sotchk',
    'HK6_sotchk',
    'HK7_sotchk',
    'HK8_sotchk',
    'HK9_sotchk',
    'HK10_sotchk',
    'HK11_sotchk',
    'HK12_sotchk']

NUM_FEATURES_NEW = ['AverageDTBHK', 'AverageSOTCHK', 'AverageDRL', 'NumSems',
       'performance_cluster', 'WeightedPerformance', 'SlopeDTBHK',
       'SlopeSOTCHK', 'SlopeDRL', 'StabilityDTBHK', 'StabilitySOTCHK',
       'StabilityDRL', 'SlopeToStabilityDTBHK', 'SlopeToStabilitySOTCHK',
       'SlopeToStabilityDRL']